// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
)

// APIGroupApplyConfiguration represents a declarative configuration of the APIGroup type for use
// with apply.
type APIGroupApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	Name                       *string                                        `json:"name,omitempty"`
	Versions                   *[]GroupVersionForDiscoveryApplyConfiguration  `json:"versions,omitempty"`
	PreferredVersion           *GroupVersionForDiscoveryApplyConfiguration    `json:"preferredVersion,omitempty"`
	ServerAddressByClientCIDRs *[]ServerAddressByClientCIDRApplyConfiguration `json:"serverAddressByClientCIDRs,omitempty"`
}

// APIGroupApplyConfiguration represents a declarative configuration of the APIGroup type for use
// with apply.
func APIGroup() *APIGroupApplyConfiguration {
	return &APIGroupApplyConfiguration{}
}

// APIGroupList represents a listAlias of APIGroupApplyConfiguration.
type APIGroupList []*APIGroupApplyConfiguration

// APIGroupMap represents a map of APIGroupApplyConfiguration.
type APIGroupMap map[string]APIGroupApplyConfiguration

// APIGroupListApplyConfiguration represents a declarative configuration of the APIGroupList type for use
// with apply.
type APIGroupListApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	Groups                     *[]APIGroupApplyConfiguration `json:"groups,omitempty"`
}

// APIGroupListApplyConfiguration represents a declarative configuration of the APIGroupList type for use
// with apply.
func APIGroupList() *APIGroupListApplyConfiguration {
	return &APIGroupListApplyConfiguration{}
}

// APIGroupListList represents a listAlias of APIGroupListApplyConfiguration.
type APIGroupListList []*APIGroupListApplyConfiguration

// APIGroupListMap represents a map of APIGroupListApplyConfiguration.
type APIGroupListMap map[string]APIGroupListApplyConfiguration

// APIResourceApplyConfiguration represents a declarative configuration of the APIResource type for use
// with apply.
type APIResourceApplyConfiguration struct {
	Name               *string       `json:"name,omitempty"`
	SingularName       *string       `json:"singularName,omitempty"`
	Namespaced         *bool         `json:"namespaced,omitempty"`
	Group              *string       `json:"group,omitempty"`
	Version            *string       `json:"version,omitempty"`
	Kind               *string       `json:"kind,omitempty"`
	Verbs              *metav1.Verbs `json:"verbs,omitempty"`
	ShortNames         *[]string     `json:"shortNames,omitempty"`
	Categories         *[]string     `json:"categories,omitempty"`
	StorageVersionHash *string       `json:"storageVersionHash,omitempty"`
}

// APIResourceApplyConfiguration represents a declarative configuration of the APIResource type for use
// with apply.
func APIResource() *APIResourceApplyConfiguration {
	return &APIResourceApplyConfiguration{}
}

// APIResourceList represents a listAlias of APIResourceApplyConfiguration.
type APIResourceList []*APIResourceApplyConfiguration

// APIResourceMap represents a map of APIResourceApplyConfiguration.
type APIResourceMap map[string]APIResourceApplyConfiguration

// APIResourceListApplyConfiguration represents a declarative configuration of the APIResourceList type for use
// with apply.
type APIResourceListApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	GroupVersion               *string                          `json:"groupVersion,omitempty"`
	APIResources               *[]APIResourceApplyConfiguration `json:"resources,omitempty"`
}

// APIResourceListApplyConfiguration represents a declarative configuration of the APIResourceList type for use
// with apply.
func APIResourceList() *APIResourceListApplyConfiguration {
	return &APIResourceListApplyConfiguration{}
}

// APIResourceListList represents a listAlias of APIResourceListApplyConfiguration.
type APIResourceListList []*APIResourceListApplyConfiguration

// APIResourceListMap represents a map of APIResourceListApplyConfiguration.
type APIResourceListMap map[string]APIResourceListApplyConfiguration

// APIVersionsApplyConfiguration represents a declarative configuration of the APIVersions type for use
// with apply.
type APIVersionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	Versions                   *[]string                                      `json:"versions,omitempty"`
	ServerAddressByClientCIDRs *[]ServerAddressByClientCIDRApplyConfiguration `json:"serverAddressByClientCIDRs,omitempty"`
}

// APIVersionsApplyConfiguration represents a declarative configuration of the APIVersions type for use
// with apply.
func APIVersions() *APIVersionsApplyConfiguration {
	return &APIVersionsApplyConfiguration{}
}

// APIVersionsList represents a listAlias of APIVersionsApplyConfiguration.
type APIVersionsList []*APIVersionsApplyConfiguration

// APIVersionsMap represents a map of APIVersionsApplyConfiguration.
type APIVersionsMap map[string]APIVersionsApplyConfiguration

// CreateOptionsApplyConfiguration represents a declarative configuration of the CreateOptions type for use
// with apply.
type CreateOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	DryRun                     *[]string `json:"dryRun,omitempty"`
	FieldManager               *string   `json:"fieldManager,omitempty"`
}

// CreateOptionsApplyConfiguration represents a declarative configuration of the CreateOptions type for use
// with apply.
func CreateOptions() *CreateOptionsApplyConfiguration {
	return &CreateOptionsApplyConfiguration{}
}

// CreateOptionsList represents a listAlias of CreateOptionsApplyConfiguration.
type CreateOptionsList []*CreateOptionsApplyConfiguration

// CreateOptionsMap represents a map of CreateOptionsApplyConfiguration.
type CreateOptionsMap map[string]CreateOptionsApplyConfiguration

// DeleteOptionsApplyConfiguration represents a declarative configuration of the DeleteOptions type for use
// with apply.
type DeleteOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	GracePeriodSeconds         *int64                           `json:"gracePeriodSeconds,omitempty"`
	Preconditions              *PreconditionsApplyConfiguration `json:"preconditions,omitempty"`
	OrphanDependents           *bool                            `json:"orphanDependents,omitempty"`
	PropagationPolicy          *metav1.DeletionPropagation      `json:"propagationPolicy,omitempty"`
	DryRun                     *[]string                        `json:"dryRun,omitempty"`
}

// DeleteOptionsApplyConfiguration represents a declarative configuration of the DeleteOptions type for use
// with apply.
func DeleteOptions() *DeleteOptionsApplyConfiguration {
	return &DeleteOptionsApplyConfiguration{}
}

// DeleteOptionsList represents a listAlias of DeleteOptionsApplyConfiguration.
type DeleteOptionsList []*DeleteOptionsApplyConfiguration

// DeleteOptionsMap represents a map of DeleteOptionsApplyConfiguration.
type DeleteOptionsMap map[string]DeleteOptionsApplyConfiguration

// ExportOptionsApplyConfiguration represents a declarative configuration of the ExportOptions type for use
// with apply.
type ExportOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	Export                     *bool `json:"export,omitempty"`
	Exact                      *bool `json:"exact,omitempty"`
}

// ExportOptionsApplyConfiguration represents a declarative configuration of the ExportOptions type for use
// with apply.
func ExportOptions() *ExportOptionsApplyConfiguration {
	return &ExportOptionsApplyConfiguration{}
}

// ExportOptionsList represents a listAlias of ExportOptionsApplyConfiguration.
type ExportOptionsList []*ExportOptionsApplyConfiguration

// ExportOptionsMap represents a map of ExportOptionsApplyConfiguration.
type ExportOptionsMap map[string]ExportOptionsApplyConfiguration

// GetOptionsApplyConfiguration represents a declarative configuration of the GetOptions type for use
// with apply.
type GetOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	ResourceVersion            *string `json:"resourceVersion,omitempty"`
}

// GetOptionsApplyConfiguration represents a declarative configuration of the GetOptions type for use
// with apply.
func GetOptions() *GetOptionsApplyConfiguration {
	return &GetOptionsApplyConfiguration{}
}

// GetOptionsList represents a listAlias of GetOptionsApplyConfiguration.
type GetOptionsList []*GetOptionsApplyConfiguration

// GetOptionsMap represents a map of GetOptionsApplyConfiguration.
type GetOptionsMap map[string]GetOptionsApplyConfiguration

// GroupKindApplyConfiguration represents a declarative configuration of the GroupKind type for use
// with apply.
type GroupKindApplyConfiguration struct {
	Group *string `json:"group,omitempty"`
	Kind  *string `json:"kind,omitempty"`
}

// GroupKindApplyConfiguration represents a declarative configuration of the GroupKind type for use
// with apply.
func GroupKind() *GroupKindApplyConfiguration {
	return &GroupKindApplyConfiguration{}
}

// GroupKindList represents a listAlias of GroupKindApplyConfiguration.
type GroupKindList []*GroupKindApplyConfiguration

// GroupKindMap represents a map of GroupKindApplyConfiguration.
type GroupKindMap map[string]GroupKindApplyConfiguration

// GroupResourceApplyConfiguration represents a declarative configuration of the GroupResource type for use
// with apply.
type GroupResourceApplyConfiguration struct {
	Group    *string `json:"group,omitempty"`
	Resource *string `json:"resource,omitempty"`
}

// GroupResourceApplyConfiguration represents a declarative configuration of the GroupResource type for use
// with apply.
func GroupResource() *GroupResourceApplyConfiguration {
	return &GroupResourceApplyConfiguration{}
}

// GroupResourceList represents a listAlias of GroupResourceApplyConfiguration.
type GroupResourceList []*GroupResourceApplyConfiguration

// GroupResourceMap represents a map of GroupResourceApplyConfiguration.
type GroupResourceMap map[string]GroupResourceApplyConfiguration

// GroupVersionApplyConfiguration represents a declarative configuration of the GroupVersion type for use
// with apply.
type GroupVersionApplyConfiguration struct {
	Group   *string `json:"group,omitempty"`
	Version *string `json:"version,omitempty"`
}

// GroupVersionApplyConfiguration represents a declarative configuration of the GroupVersion type for use
// with apply.
func GroupVersion() *GroupVersionApplyConfiguration {
	return &GroupVersionApplyConfiguration{}
}

// GroupVersionList represents a listAlias of GroupVersionApplyConfiguration.
type GroupVersionList []*GroupVersionApplyConfiguration

// GroupVersionMap represents a map of GroupVersionApplyConfiguration.
type GroupVersionMap map[string]GroupVersionApplyConfiguration

// GroupVersionForDiscoveryApplyConfiguration represents a declarative configuration of the GroupVersionForDiscovery type for use
// with apply.
type GroupVersionForDiscoveryApplyConfiguration struct {
	GroupVersion *string `json:"groupVersion,omitempty"`
	Version      *string `json:"version,omitempty"`
}

// GroupVersionForDiscoveryApplyConfiguration represents a declarative configuration of the GroupVersionForDiscovery type for use
// with apply.
func GroupVersionForDiscovery() *GroupVersionForDiscoveryApplyConfiguration {
	return &GroupVersionForDiscoveryApplyConfiguration{}
}

// GroupVersionForDiscoveryList represents a listAlias of GroupVersionForDiscoveryApplyConfiguration.
type GroupVersionForDiscoveryList []*GroupVersionForDiscoveryApplyConfiguration

// GroupVersionForDiscoveryMap represents a map of GroupVersionForDiscoveryApplyConfiguration.
type GroupVersionForDiscoveryMap map[string]GroupVersionForDiscoveryApplyConfiguration

// GroupVersionKindApplyConfiguration represents a declarative configuration of the GroupVersionKind type for use
// with apply.
type GroupVersionKindApplyConfiguration struct {
	Group   *string `json:"group,omitempty"`
	Version *string `json:"version,omitempty"`
	Kind    *string `json:"kind,omitempty"`
}

// GroupVersionKindApplyConfiguration represents a declarative configuration of the GroupVersionKind type for use
// with apply.
func GroupVersionKind() *GroupVersionKindApplyConfiguration {
	return &GroupVersionKindApplyConfiguration{}
}

// GroupVersionKindList represents a listAlias of GroupVersionKindApplyConfiguration.
type GroupVersionKindList []*GroupVersionKindApplyConfiguration

// GroupVersionKindMap represents a map of GroupVersionKindApplyConfiguration.
type GroupVersionKindMap map[string]GroupVersionKindApplyConfiguration

// GroupVersionResourceApplyConfiguration represents a declarative configuration of the GroupVersionResource type for use
// with apply.
type GroupVersionResourceApplyConfiguration struct {
	Group    *string `json:"group,omitempty"`
	Version  *string `json:"version,omitempty"`
	Resource *string `json:"resource,omitempty"`
}

// GroupVersionResourceApplyConfiguration represents a declarative configuration of the GroupVersionResource type for use
// with apply.
func GroupVersionResource() *GroupVersionResourceApplyConfiguration {
	return &GroupVersionResourceApplyConfiguration{}
}

// GroupVersionResourceList represents a listAlias of GroupVersionResourceApplyConfiguration.
type GroupVersionResourceList []*GroupVersionResourceApplyConfiguration

// GroupVersionResourceMap represents a map of GroupVersionResourceApplyConfiguration.
type GroupVersionResourceMap map[string]GroupVersionResourceApplyConfiguration

// LabelSelectorApplyConfiguration represents a declarative configuration of the LabelSelector type for use
// with apply.
type LabelSelectorApplyConfiguration struct {
	MatchLabels      *map[string]string                            `json:"matchLabels,omitempty"`
	MatchExpressions *[]LabelSelectorRequirementApplyConfiguration `json:"matchExpressions,omitempty"`
}

// LabelSelectorApplyConfiguration represents a declarative configuration of the LabelSelector type for use
// with apply.
func LabelSelector() *LabelSelectorApplyConfiguration {
	return &LabelSelectorApplyConfiguration{}
}

// LabelSelectorList represents a listAlias of LabelSelectorApplyConfiguration.
type LabelSelectorList []*LabelSelectorApplyConfiguration

// LabelSelectorMap represents a map of LabelSelectorApplyConfiguration.
type LabelSelectorMap map[string]LabelSelectorApplyConfiguration

// LabelSelectorRequirementApplyConfiguration represents a declarative configuration of the LabelSelectorRequirement type for use
// with apply.
type LabelSelectorRequirementApplyConfiguration struct {
	Key      *string                       `json:"key,omitempty"`
	Operator *metav1.LabelSelectorOperator `json:"operator,omitempty"`
	Values   *[]string                     `json:"values,omitempty"`
}

// LabelSelectorRequirementApplyConfiguration represents a declarative configuration of the LabelSelectorRequirement type for use
// with apply.
func LabelSelectorRequirement() *LabelSelectorRequirementApplyConfiguration {
	return &LabelSelectorRequirementApplyConfiguration{}
}

// LabelSelectorRequirementList represents a listAlias of LabelSelectorRequirementApplyConfiguration.
type LabelSelectorRequirementList []*LabelSelectorRequirementApplyConfiguration

// LabelSelectorRequirementMap represents a map of LabelSelectorRequirementApplyConfiguration.
type LabelSelectorRequirementMap map[string]LabelSelectorRequirementApplyConfiguration

// ListApplyConfiguration represents a declarative configuration of the List type for use
// with apply.
type ListApplyConfiguration struct {
	TypeMetaApplyConfiguration  `json:",inline"`
	*ListMetaApplyConfiguration `json:"metadata,omitempty"`
	Items                       *[]runtime.RawExtension `json:"items,omitempty"`
}

// ListApplyConfiguration represents a declarative configuration of the List type for use
// with apply.
func List() *ListApplyConfiguration {
	return &ListApplyConfiguration{}
}

// ListList represents a listAlias of ListApplyConfiguration.
type ListList []*ListApplyConfiguration

// ListMap represents a map of ListApplyConfiguration.
type ListMap map[string]ListApplyConfiguration

// ListMetaApplyConfiguration represents a declarative configuration of the ListMeta type for use
// with apply.
type ListMetaApplyConfiguration struct {
	SelfLink           *string `json:"selfLink,omitempty"`
	ResourceVersion    *string `json:"resourceVersion,omitempty"`
	Continue           *string `json:"continue,omitempty"`
	RemainingItemCount *int64  `json:"remainingItemCount,omitempty"`
}

// ListMetaApplyConfiguration represents a declarative configuration of the ListMeta type for use
// with apply.
func ListMeta() *ListMetaApplyConfiguration {
	return &ListMetaApplyConfiguration{}
}

// ListMetaList represents a listAlias of ListMetaApplyConfiguration.
type ListMetaList []*ListMetaApplyConfiguration

// ListMetaMap represents a map of ListMetaApplyConfiguration.
type ListMetaMap map[string]ListMetaApplyConfiguration

// ListOptionsApplyConfiguration represents a declarative configuration of the ListOptions type for use
// with apply.
type ListOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	LabelSelector              *string `json:"labelSelector,omitempty"`
	FieldSelector              *string `json:"fieldSelector,omitempty"`
	Watch                      *bool   `json:"watch,omitempty"`
	AllowWatchBookmarks        *bool   `json:"allowWatchBookmarks,omitempty"`
	ResourceVersion            *string `json:"resourceVersion,omitempty"`
	TimeoutSeconds             *int64  `json:"timeoutSeconds,omitempty"`
	Limit                      *int64  `json:"limit,omitempty"`
	Continue                   *string `json:"continue,omitempty"`
}

// ListOptionsApplyConfiguration represents a declarative configuration of the ListOptions type for use
// with apply.
func ListOptions() *ListOptionsApplyConfiguration {
	return &ListOptionsApplyConfiguration{}
}

// ListOptionsList represents a listAlias of ListOptionsApplyConfiguration.
type ListOptionsList []*ListOptionsApplyConfiguration

// ListOptionsMap represents a map of ListOptionsApplyConfiguration.
type ListOptionsMap map[string]ListOptionsApplyConfiguration

// ManagedFieldsEntryApplyConfiguration represents a declarative configuration of the ManagedFieldsEntry type for use
// with apply.
type ManagedFieldsEntryApplyConfiguration struct {
	Manager    *string                            `json:"manager,omitempty"`
	Operation  *metav1.ManagedFieldsOperationType `json:"operation,omitempty"`
	APIVersion *string                            `json:"apiVersion,omitempty"`
	Time       *metav1.Time                       `json:"time,omitempty"`
	FieldsType *string                            `json:"fieldsType,omitempty"`
	FieldsV1   *metav1.FieldsV1                   `json:"fieldsV1,omitempty"`
}

// ManagedFieldsEntryApplyConfiguration represents a declarative configuration of the ManagedFieldsEntry type for use
// with apply.
func ManagedFieldsEntry() *ManagedFieldsEntryApplyConfiguration {
	return &ManagedFieldsEntryApplyConfiguration{}
}

// ManagedFieldsEntryList represents a listAlias of ManagedFieldsEntryApplyConfiguration.
type ManagedFieldsEntryList []*ManagedFieldsEntryApplyConfiguration

// ManagedFieldsEntryMap represents a map of ManagedFieldsEntryApplyConfiguration.
type ManagedFieldsEntryMap map[string]ManagedFieldsEntryApplyConfiguration

// ObjectMetaApplyConfiguration represents a declarative configuration of the ObjectMeta type for use
// with apply.
type ObjectMetaApplyConfiguration struct {
	Name                       *string                                 `json:"name,omitempty"`
	GenerateName               *string                                 `json:"generateName,omitempty"`
	Namespace                  *string                                 `json:"namespace,omitempty"`
	SelfLink                   *string                                 `json:"selfLink,omitempty"`
	UID                        *types.UID                              `json:"uid,omitempty"`
	ResourceVersion            *string                                 `json:"resourceVersion,omitempty"`
	Generation                 *int64                                  `json:"generation,omitempty"`
	CreationTimestamp          *metav1.Time                            `json:"creationTimestamp,omitempty"`
	DeletionTimestamp          *metav1.Time                            `json:"deletionTimestamp,omitempty"`
	DeletionGracePeriodSeconds *int64                                  `json:"deletionGracePeriodSeconds,omitempty"`
	Labels                     *map[string]string                      `json:"labels,omitempty"`
	Annotations                *map[string]string                      `json:"annotations,omitempty"`
	OwnerReferences            *[]OwnerReferenceApplyConfiguration     `json:"ownerReferences,omitempty"`
	Finalizers                 *[]string                               `json:"finalizers,omitempty"`
	ClusterName                *string                                 `json:"clusterName,omitempty"`
	ManagedFields              *[]ManagedFieldsEntryApplyConfiguration `json:"managedFields,omitempty"`
}

// ObjectMetaApplyConfiguration represents a declarative configuration of the ObjectMeta type for use
// with apply.
func ObjectMeta() *ObjectMetaApplyConfiguration {
	return &ObjectMetaApplyConfiguration{}
}

// ObjectMetaList represents a listAlias of ObjectMetaApplyConfiguration.
type ObjectMetaList []*ObjectMetaApplyConfiguration

// ObjectMetaMap represents a map of ObjectMetaApplyConfiguration.
type ObjectMetaMap map[string]ObjectMetaApplyConfiguration

// OwnerReferenceApplyConfiguration represents a declarative configuration of the OwnerReference type for use
// with apply.
type OwnerReferenceApplyConfiguration struct {
	APIVersion         *string    `json:"apiVersion,omitempty"`
	Kind               *string    `json:"kind,omitempty"`
	Name               *string    `json:"name,omitempty"`
	UID                *types.UID `json:"uid,omitempty"`
	Controller         *bool      `json:"controller,omitempty"`
	BlockOwnerDeletion *bool      `json:"blockOwnerDeletion,omitempty"`
}

// OwnerReferenceApplyConfiguration represents a declarative configuration of the OwnerReference type for use
// with apply.
func OwnerReference() *OwnerReferenceApplyConfiguration {
	return &OwnerReferenceApplyConfiguration{}
}

// OwnerReferenceList represents a listAlias of OwnerReferenceApplyConfiguration.
type OwnerReferenceList []*OwnerReferenceApplyConfiguration

// OwnerReferenceMap represents a map of OwnerReferenceApplyConfiguration.
type OwnerReferenceMap map[string]OwnerReferenceApplyConfiguration

// PartialObjectMetadataApplyConfiguration represents a declarative configuration of the PartialObjectMetadata type for use
// with apply.
type PartialObjectMetadataApplyConfiguration struct {
	TypeMetaApplyConfiguration    `json:",inline"`
	*ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
}

// PartialObjectMetadataApplyConfiguration represents a declarative configuration of the PartialObjectMetadata type for use
// with apply.
func PartialObjectMetadata() *PartialObjectMetadataApplyConfiguration {
	return &PartialObjectMetadataApplyConfiguration{}
}

// PartialObjectMetadataList represents a listAlias of PartialObjectMetadataApplyConfiguration.
type PartialObjectMetadataList []*PartialObjectMetadataApplyConfiguration

// PartialObjectMetadataMap represents a map of PartialObjectMetadataApplyConfiguration.
type PartialObjectMetadataMap map[string]PartialObjectMetadataApplyConfiguration

// PartialObjectMetadataListApplyConfiguration represents a declarative configuration of the PartialObjectMetadataList type for use
// with apply.
type PartialObjectMetadataListApplyConfiguration struct {
	TypeMetaApplyConfiguration  `json:",inline"`
	*ListMetaApplyConfiguration `json:"metadata,omitempty"`
	Items                       *[]PartialObjectMetadataApplyConfiguration `json:"items,omitempty"`
}

// PartialObjectMetadataListApplyConfiguration represents a declarative configuration of the PartialObjectMetadataList type for use
// with apply.
func PartialObjectMetadataList() *PartialObjectMetadataListApplyConfiguration {
	return &PartialObjectMetadataListApplyConfiguration{}
}

// PartialObjectMetadataListList represents a listAlias of PartialObjectMetadataListApplyConfiguration.
type PartialObjectMetadataListList []*PartialObjectMetadataListApplyConfiguration

// PartialObjectMetadataListMap represents a map of PartialObjectMetadataListApplyConfiguration.
type PartialObjectMetadataListMap map[string]PartialObjectMetadataListApplyConfiguration

// PatchOptionsApplyConfiguration represents a declarative configuration of the PatchOptions type for use
// with apply.
type PatchOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	DryRun                     *[]string `json:"dryRun,omitempty"`
	Force                      *bool     `json:"force,omitempty"`
	FieldManager               *string   `json:"fieldManager,omitempty"`
}

// PatchOptionsApplyConfiguration represents a declarative configuration of the PatchOptions type for use
// with apply.
func PatchOptions() *PatchOptionsApplyConfiguration {
	return &PatchOptionsApplyConfiguration{}
}

// PatchOptionsList represents a listAlias of PatchOptionsApplyConfiguration.
type PatchOptionsList []*PatchOptionsApplyConfiguration

// PatchOptionsMap represents a map of PatchOptionsApplyConfiguration.
type PatchOptionsMap map[string]PatchOptionsApplyConfiguration

// PreconditionsApplyConfiguration represents a declarative configuration of the Preconditions type for use
// with apply.
type PreconditionsApplyConfiguration struct {
	UID             *types.UID `json:"uid,omitempty"`
	ResourceVersion *string    `json:"resourceVersion,omitempty"`
}

// PreconditionsApplyConfiguration represents a declarative configuration of the Preconditions type for use
// with apply.
func Preconditions() *PreconditionsApplyConfiguration {
	return &PreconditionsApplyConfiguration{}
}

// PreconditionsList represents a listAlias of PreconditionsApplyConfiguration.
type PreconditionsList []*PreconditionsApplyConfiguration

// PreconditionsMap represents a map of PreconditionsApplyConfiguration.
type PreconditionsMap map[string]PreconditionsApplyConfiguration

// RootPathsApplyConfiguration represents a declarative configuration of the RootPaths type for use
// with apply.
type RootPathsApplyConfiguration struct {
	Paths *[]string `json:"paths,omitempty"`
}

// RootPathsApplyConfiguration represents a declarative configuration of the RootPaths type for use
// with apply.
func RootPaths() *RootPathsApplyConfiguration {
	return &RootPathsApplyConfiguration{}
}

// RootPathsList represents a listAlias of RootPathsApplyConfiguration.
type RootPathsList []*RootPathsApplyConfiguration

// RootPathsMap represents a map of RootPathsApplyConfiguration.
type RootPathsMap map[string]RootPathsApplyConfiguration

// ServerAddressByClientCIDRApplyConfiguration represents a declarative configuration of the ServerAddressByClientCIDR type for use
// with apply.
type ServerAddressByClientCIDRApplyConfiguration struct {
	ClientCIDR    *string `json:"clientCIDR,omitempty"`
	ServerAddress *string `json:"serverAddress,omitempty"`
}

// ServerAddressByClientCIDRApplyConfiguration represents a declarative configuration of the ServerAddressByClientCIDR type for use
// with apply.
func ServerAddressByClientCIDR() *ServerAddressByClientCIDRApplyConfiguration {
	return &ServerAddressByClientCIDRApplyConfiguration{}
}

// ServerAddressByClientCIDRList represents a listAlias of ServerAddressByClientCIDRApplyConfiguration.
type ServerAddressByClientCIDRList []*ServerAddressByClientCIDRApplyConfiguration

// ServerAddressByClientCIDRMap represents a map of ServerAddressByClientCIDRApplyConfiguration.
type ServerAddressByClientCIDRMap map[string]ServerAddressByClientCIDRApplyConfiguration

// StatusApplyConfiguration represents a declarative configuration of the Status type for use
// with apply.
type StatusApplyConfiguration struct {
	TypeMetaApplyConfiguration  `json:",inline"`
	*ListMetaApplyConfiguration `json:"metadata,omitempty"`
	Status                      *string                          `json:"status,omitempty"`
	Message                     *string                          `json:"message,omitempty"`
	Reason                      *metav1.StatusReason             `json:"reason,omitempty"`
	Details                     *StatusDetailsApplyConfiguration `json:"details,omitempty"`
	Code                        *int32                           `json:"code,omitempty"`
}

// StatusApplyConfiguration represents a declarative configuration of the Status type for use
// with apply.
func Status() *StatusApplyConfiguration {
	return &StatusApplyConfiguration{}
}

// StatusList represents a listAlias of StatusApplyConfiguration.
type StatusList []*StatusApplyConfiguration

// StatusMap represents a map of StatusApplyConfiguration.
type StatusMap map[string]StatusApplyConfiguration

// StatusCauseApplyConfiguration represents a declarative configuration of the StatusCause type for use
// with apply.
type StatusCauseApplyConfiguration struct {
	Type    *metav1.CauseType `json:"reason,omitempty"`
	Message *string           `json:"message,omitempty"`
	Field   *string           `json:"field,omitempty"`
}

// StatusCauseApplyConfiguration represents a declarative configuration of the StatusCause type for use
// with apply.
func StatusCause() *StatusCauseApplyConfiguration {
	return &StatusCauseApplyConfiguration{}
}

// StatusCauseList represents a listAlias of StatusCauseApplyConfiguration.
type StatusCauseList []*StatusCauseApplyConfiguration

// StatusCauseMap represents a map of StatusCauseApplyConfiguration.
type StatusCauseMap map[string]StatusCauseApplyConfiguration

// StatusDetailsApplyConfiguration represents a declarative configuration of the StatusDetails type for use
// with apply.
type StatusDetailsApplyConfiguration struct {
	Name              *string                          `json:"name,omitempty"`
	Group             *string                          `json:"group,omitempty"`
	Kind              *string                          `json:"kind,omitempty"`
	UID               *types.UID                       `json:"uid,omitempty"`
	Causes            *[]StatusCauseApplyConfiguration `json:"causes,omitempty"`
	RetryAfterSeconds *int32                           `json:"retryAfterSeconds,omitempty"`
}

// StatusDetailsApplyConfiguration represents a declarative configuration of the StatusDetails type for use
// with apply.
func StatusDetails() *StatusDetailsApplyConfiguration {
	return &StatusDetailsApplyConfiguration{}
}

// StatusDetailsList represents a listAlias of StatusDetailsApplyConfiguration.
type StatusDetailsList []*StatusDetailsApplyConfiguration

// StatusDetailsMap represents a map of StatusDetailsApplyConfiguration.
type StatusDetailsMap map[string]StatusDetailsApplyConfiguration

// TableApplyConfiguration represents a declarative configuration of the Table type for use
// with apply.
type TableApplyConfiguration struct {
	TypeMetaApplyConfiguration  `json:",inline"`
	*ListMetaApplyConfiguration `json:"metadata,omitempty"`
	ColumnDefinitions           *[]TableColumnDefinitionApplyConfiguration `json:"columnDefinitions,omitempty"`
	Rows                        *[]TableRowApplyConfiguration              `json:"rows,omitempty"`
}

// TableApplyConfiguration represents a declarative configuration of the Table type for use
// with apply.
func Table() *TableApplyConfiguration {
	return &TableApplyConfiguration{}
}

// TableList represents a listAlias of TableApplyConfiguration.
type TableList []*TableApplyConfiguration

// TableMap represents a map of TableApplyConfiguration.
type TableMap map[string]TableApplyConfiguration

// TableColumnDefinitionApplyConfiguration represents a declarative configuration of the TableColumnDefinition type for use
// with apply.
type TableColumnDefinitionApplyConfiguration struct {
	Name        *string `json:"name,omitempty"`
	Type        *string `json:"type,omitempty"`
	Format      *string `json:"format,omitempty"`
	Description *string `json:"description,omitempty"`
	Priority    *int32  `json:"priority,omitempty"`
}

// TableColumnDefinitionApplyConfiguration represents a declarative configuration of the TableColumnDefinition type for use
// with apply.
func TableColumnDefinition() *TableColumnDefinitionApplyConfiguration {
	return &TableColumnDefinitionApplyConfiguration{}
}

// TableColumnDefinitionList represents a listAlias of TableColumnDefinitionApplyConfiguration.
type TableColumnDefinitionList []*TableColumnDefinitionApplyConfiguration

// TableColumnDefinitionMap represents a map of TableColumnDefinitionApplyConfiguration.
type TableColumnDefinitionMap map[string]TableColumnDefinitionApplyConfiguration

// TableOptionsApplyConfiguration represents a declarative configuration of the TableOptions type for use
// with apply.
type TableOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	IncludeObject              *metav1.IncludeObjectPolicy `json:"includeObject,omitempty"`
}

// TableOptionsApplyConfiguration represents a declarative configuration of the TableOptions type for use
// with apply.
func TableOptions() *TableOptionsApplyConfiguration {
	return &TableOptionsApplyConfiguration{}
}

// TableOptionsList represents a listAlias of TableOptionsApplyConfiguration.
type TableOptionsList []*TableOptionsApplyConfiguration

// TableOptionsMap represents a map of TableOptionsApplyConfiguration.
type TableOptionsMap map[string]TableOptionsApplyConfiguration

// TableRowApplyConfiguration represents a declarative configuration of the TableRow type for use
// with apply.
type TableRowApplyConfiguration struct {
	Cells      *[]interface{}                         `json:"cells,omitempty"`
	Conditions *[]TableRowConditionApplyConfiguration `json:"conditions,omitempty"`
	Object     *runtime.RawExtension                  `json:"object,omitempty"`
}

// TableRowApplyConfiguration represents a declarative configuration of the TableRow type for use
// with apply.
func TableRow() *TableRowApplyConfiguration {
	return &TableRowApplyConfiguration{}
}

// TableRowList represents a listAlias of TableRowApplyConfiguration.
type TableRowList []*TableRowApplyConfiguration

// TableRowMap represents a map of TableRowApplyConfiguration.
type TableRowMap map[string]TableRowApplyConfiguration

// TableRowConditionApplyConfiguration represents a declarative configuration of the TableRowCondition type for use
// with apply.
type TableRowConditionApplyConfiguration struct {
	Type    *metav1.RowConditionType `json:"type,omitempty"`
	Status  *metav1.ConditionStatus  `json:"status,omitempty"`
	Reason  *string                  `json:"reason,omitempty"`
	Message *string                  `json:"message,omitempty"`
}

// TableRowConditionApplyConfiguration represents a declarative configuration of the TableRowCondition type for use
// with apply.
func TableRowCondition() *TableRowConditionApplyConfiguration {
	return &TableRowConditionApplyConfiguration{}
}

// TableRowConditionList represents a listAlias of TableRowConditionApplyConfiguration.
type TableRowConditionList []*TableRowConditionApplyConfiguration

// TableRowConditionMap represents a map of TableRowConditionApplyConfiguration.
type TableRowConditionMap map[string]TableRowConditionApplyConfiguration

// TimestampApplyConfiguration represents a declarative configuration of the Timestamp type for use
// with apply.
type TimestampApplyConfiguration struct {
	Seconds *int64 `json:"seconds,omitempty"`
	Nanos   *int32 `json:"nanos,omitempty"`
}

// TimestampApplyConfiguration represents a declarative configuration of the Timestamp type for use
// with apply.
func Timestamp() *TimestampApplyConfiguration {
	return &TimestampApplyConfiguration{}
}

// TimestampList represents a listAlias of TimestampApplyConfiguration.
type TimestampList []*TimestampApplyConfiguration

// TimestampMap represents a map of TimestampApplyConfiguration.
type TimestampMap map[string]TimestampApplyConfiguration

// TypeMetaApplyConfiguration represents a declarative configuration of the TypeMeta type for use
// with apply.
type TypeMetaApplyConfiguration struct {
	Kind       *string `json:"kind,omitempty"`
	APIVersion *string `json:"apiVersion,omitempty"`
}

// TypeMetaApplyConfiguration represents a declarative configuration of the TypeMeta type for use
// with apply.
func TypeMeta() *TypeMetaApplyConfiguration {
	return &TypeMetaApplyConfiguration{}
}

// TypeMetaList represents a listAlias of TypeMetaApplyConfiguration.
type TypeMetaList []*TypeMetaApplyConfiguration

// TypeMetaMap represents a map of TypeMetaApplyConfiguration.
type TypeMetaMap map[string]TypeMetaApplyConfiguration

// UpdateOptionsApplyConfiguration represents a declarative configuration of the UpdateOptions type for use
// with apply.
type UpdateOptionsApplyConfiguration struct {
	TypeMetaApplyConfiguration `json:",inline"`
	DryRun                     *[]string `json:"dryRun,omitempty"`
	FieldManager               *string   `json:"fieldManager,omitempty"`
}

// UpdateOptionsApplyConfiguration represents a declarative configuration of the UpdateOptions type for use
// with apply.
func UpdateOptions() *UpdateOptionsApplyConfiguration {
	return &UpdateOptionsApplyConfiguration{}
}

// UpdateOptionsList represents a listAlias of UpdateOptionsApplyConfiguration.
type UpdateOptionsList []*UpdateOptionsApplyConfiguration

// UpdateOptionsMap represents a map of UpdateOptionsApplyConfiguration.
type UpdateOptionsMap map[string]UpdateOptionsApplyConfiguration

// WatchEventApplyConfiguration represents a declarative configuration of the WatchEvent type for use
// with apply.
type WatchEventApplyConfiguration struct {
	Type   *string               `json:"type,omitempty"`
	Object *runtime.RawExtension `json:"object,omitempty"`
}

// WatchEventApplyConfiguration represents a declarative configuration of the WatchEvent type for use
// with apply.
func WatchEvent() *WatchEventApplyConfiguration {
	return &WatchEventApplyConfiguration{}
}

// WatchEventList represents a listAlias of WatchEventApplyConfiguration.
type WatchEventList []*WatchEventApplyConfiguration

// WatchEventMap represents a map of WatchEventApplyConfiguration.
type WatchEventMap map[string]WatchEventApplyConfiguration
